import type { Metadata } from "next";
import "./globals.css";
import { Besley } from "next/font/google";
import { AuthContextProvider } from '@/contexts/auth-context';
import Navbar from "@/components/header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const besley = Besley({
  subsets: ["latin"],
  variable: "--font-besley", // 這就是關鍵名稱
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-full flex-col ${besley.variable}`}>
        <Navbar className="mb-[100px]"/>
        <AuthContextProvider>{children}</AuthContextProvider>
        <Footer/>
      </body>
    </html>
  );
}
