import type { Metadata } from "next";
import "./globals.css";
import { Besley } from "next/font/google";
import { CartProvider } from "@/contexts/cart";
import { AuthContextProvider } from "@/contexts/auth-context";
import Header from "@/components/Header";
import FooterGuard from "@/components/FooterGuard";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const besley = Besley({
  subsets: ["latin"],
  variable: "--font-besley", // 這就是關鍵名稱
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`flex min-h-full flex-col ${besley.variable}`}>
        
        <AuthContextProvider>
          <CartProvider>
          <Header />
            {children}
          </CartProvider>
        </AuthContextProvider>
        <FooterGuard/>
      </body>
    </html>
  );
}
